package com.campuscoin.tips.repository;

import java.time.LocalDate;
import java.util.List;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Tuple;

import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Calls {@code sp_generate_tips}, the one writer of {@code user_tips} (UC-18, BR-14, BR-15).
 *
 * <p><b>Why the database generates a tip and Java does not.</b> Which tips a student should see is
 * decided by six rules in the procedure - a category over its limit, one approaching it, one rising
 * abnormally against the student's own history (BR-15), a heavy category with no budget, a savings
 * goal at risk (VĐ-04), and a student with too little data to analyse (UC-18 A1) - and every one of
 * them reads a view this application also reads. Writing those rules again in Java would be a second
 * answer to each, and the second answer would eventually disagree with the first about a threshold, a
 * month boundary or a deleted record. The procedure is also the only thing that can write the row:
 * the template text is rendered by {@code fn_render_template} and the ranking that BR-14's "top N"
 * depends on is computed inside it. Java's part is to decide <em>when</em> to call it and for whom.
 *
 * <p><b>Safe to call twice, and that is load-bearing.</b> The procedure ends with
 * {@code INSERT IGNORE} against {@code uk_tip_dedupe}, whose key is
 * {@code user_id|period_month|tip_template_id|category_id}. A tip that already exists for that
 * combination is skipped rather than duplicated, so:
 *
 * <ul>
 *   <li>A scheduled run that fires more than once in a period, or that a second instance also runs,
 *       produces the same tips and no others - which is why there is no leader election here, the
 *       same reasoning {@code RecurringScheduler} records for
 *       {@code sp_post_recurring_transactions} (BR-16).</li>
 *   <li><b>A pinned or dismissed tip is never regenerated.</b> Once a student has acted on a tip,
 *       its row exists with that {@code dedupe_key}, so a later run in the same month skips it. A
 *       dismissed tip therefore stays dismissed and a pinned tip keeps its place, rather than the
 *       next run resurrecting either - which is what makes "dismissed for good" true rather than
 *       merely true until the next tick.</li>
 * </ul>
 *
 * <p><b>{@code null} is passed for the month by the scheduled caller</b>, so the procedure uses
 * {@code CURDATE()} as the database session sees it, in the {@code +07:00} the session is pinned to
 * (VĐ-10). A JVM in another zone would otherwise disagree with the database about the current month
 * for part of every day - the same reasoning {@code RecurringScheduler} gives.
 */
@Repository
public class TipGenerationDao {

    /**
     * The students a scheduled run generates for: every account that can sign in and see a tip.
     *
     * <p><b>Filtered by role and status rather than by activity.</b> The obvious alternative - the
     * students who have spending this month - reads cheaper but is wrong at the two moments that
     * matter: the month a student starts spending (their first tips would never be generated by the
     * schedule) and the month they stop (their last tips would keep being re-ranked against figures
     * that no longer exist). A set of accounts has neither problem, and the procedure skips a student
     * with nothing to say, so the cost of a call that produces no tip is one indexed read.
     *
     * <p>A disabled account is excluded because it cannot sign in (BR-03), so a tip generated for it
     * could never be read; an administrator is excluded because tips are generated from a student's
     * own spending and reading them is a student endpoint.
     */
    private static final String SELECT_ACTIVE_STUDENTS = """
            SELECT CAST(u.id AS SIGNED) AS userId
              FROM users u
             WHERE u.role = 'STUDENT' AND u.status = 'ACTIVE'
             ORDER BY u.id
            """;

    private static final String CALL_GENERATE_TIPS =
            "CALL sp_generate_tips(:userId, :periodMonth, NULL)";

    @PersistenceContext
    private EntityManager entityManager;

    /**
     * Generates the tips for one student and month, skipping any that already exist.
     *
     * <p>{@code p_max_tips} is passed as {@code null} so BR-14's bound is the one the procedure reads
     * from {@code system_settings} ({@code tips.max_dashboard}, 3 by default). Sending a number here
     * would override configuration from code, which VĐ-05 forbids: how many tips a student sees is a
     * setting, not a constant.
     *
     * @param userId      the student to generate for
     * @param periodMonth the first day of the month, or {@code null} for the database's current month
     */
    @Transactional
    public void generateTips(Long userId, LocalDate periodMonth) {
        callGenerateTips(userId, periodMonth);
    }

    /**
     * The students a scheduled run should generate for, in a stable order.
     *
     * <p>Reads and returns; the caller decides what to do with the list. The run itself is not here
     * because a bulk generation wants a transaction per student, so that one student's failure
     * cannot roll back the tips already generated for the others - and a transaction boundary is the
     * caller's to draw, not a repository's.
     */
    @Transactional(readOnly = true)
    public List<Long> findActiveStudentIds() {
        @SuppressWarnings("unchecked")
        List<Tuple> rows = entityManager.createNativeQuery(SELECT_ACTIVE_STUDENTS, Tuple.class)
                .getResultList();

        return rows.stream()
                .map(row -> ((Number) row.get("userId")).longValue())
                .toList();
    }

    /**
     * One {@code CALL}, with the month left to the procedure when {@code periodMonth} is null.
     *
     * <p>{@code executeUpdate} rather than {@code getResultList}: the procedure returns no result
     * set, it writes rows. Reading it as a query would ask the driver for a result the procedure
     * never produces.
     *
     * <p>The transaction belongs to {@link #generateTips}, so each call in a bulk run is its own -
     * which is what lets a run continue past one student's failure with the others already committed
     * rather than rolled back with it.
     */
    private void callGenerateTips(Long userId, LocalDate periodMonth) {
        entityManager.createNativeQuery(CALL_GENERATE_TIPS)
                .setParameter("userId", userId)
                .setParameter("periodMonth", periodMonth)
                .executeUpdate();
    }
}
